//go:build !ignore_autogenerated

// Code generated by controller-gen (hand-authored equivalent for v1 bootstrap).
// Regenerate with: controller-gen object paths=./srv6egress/apis/v1/...

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies into out. Required for runtime.Object.
func (in *EgressPolicy) DeepCopyInto(out *EgressPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy.
func (in *EgressPolicy) DeepCopy() *EgressPolicy {
	if in == nil {
		return nil
	}
	out := new(EgressPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *EgressPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EgressPolicyList) DeepCopyInto(out *EgressPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EgressPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *EgressPolicyList) DeepCopy() *EgressPolicyList {
	if in == nil {
		return nil
	}
	out := new(EgressPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *EgressPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EgressPolicySpec) DeepCopyInto(out *EgressPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.DestinationCIDRs != nil {
		out.DestinationCIDRs = append([]string(nil), in.DestinationCIDRs...)
	}
	in.Egress.DeepCopyInto(&out.Egress)
}

func (in *EgressPolicySpec) DeepCopy() *EgressPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EgressPolicySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *Selector) DeepCopyInto(out *Selector) {
	*out = *in
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
	if in.PodSelector != nil {
		out.PodSelector = in.PodSelector.DeepCopy()
	}
}

func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

func (in *EgressSpec) DeepCopyInto(out *EgressSpec) {
	*out = *in
	in.EndpointSelector.DeepCopyInto(&out.EndpointSelector)
}

func (in *EgressSpec) DeepCopy() *EgressSpec {
	if in == nil {
		return nil
	}
	out := new(EgressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EndpointSelector) DeepCopyInto(out *EndpointSelector) {
	*out = *in
	if in.NodeSelector != nil {
		out.NodeSelector = in.NodeSelector.DeepCopy()
	}
}

func (in *EndpointSelector) DeepCopy() *EndpointSelector {
	if in == nil {
		return nil
	}
	out := new(EndpointSelector)
	in.DeepCopyInto(out)
	return out
}

func (in *EgressPolicyStatus) DeepCopyInto(out *EgressPolicyStatus) {
	*out = *in
	if in.SRPolicy != nil {
		out.SRPolicy = in.SRPolicy.DeepCopy()
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *EgressPolicyStatus) DeepCopy() *EgressPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EgressPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *SRPolicyStatus) DeepCopyInto(out *SRPolicyStatus) {
	*out = *in
	if in.SegmentList != nil {
		out.SegmentList = append([]string(nil), in.SegmentList...)
	}
}

func (in *SRPolicyStatus) DeepCopy() *SRPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SRPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
