// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: podinterface/podinterface.proto

package podinterface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodInterfaceLifecycle_CreatePodInterface_FullMethodName = "/podinterface.v1.PodInterfaceLifecycle/CreatePodInterface"
	PodInterfaceLifecycle_DeletePodInterface_FullMethodName = "/podinterface.v1.PodInterfaceLifecycle/DeletePodInterface"
)

// PodInterfaceLifecycleClient is the client API for PodInterfaceLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PodInterfaceLifecycle is the contract between Cilium's CNI plugin and an
// external provider that owns the L3 datapath realization of a Pod attachment.
//
// For one Pod attachment, exactly one component owns L3 realization. When this
// service is selected (CNI network configuration field "cniDatapathProvider"),
// Cilium creates no competing veth or netkit datapath for that attachment, and
// the provider is the sole owner of the interface: it creates the device,
// places it in the Pod network namespace, configures the namespace side of it
// and destroys it again.
//
// Cilium remains the authority for everything else about the attachment: the
// CNI attachment identity, IPAM, the endpoint object, its security identity,
// its policy and its lifecycle.
//
// Failures are reported as gRPC status codes. There is no success flag in any
// reply message: a reply that arrives is a reply that succeeded, so that a
// caller cannot mistake a transport-level failure for a refusal or the other
// way round.
type PodInterfaceLifecycleClient interface {
	// CreatePodInterface creates the Pod's interface and makes it usable.
	//
	// A successful reply is a publication barrier. By the time it is sent, the
	// provider has created the interface, has obtained its exact handle, has
	// published the corresponding attachment binding and has received that
	// binding's acknowledgement. The caller may therefore treat the reply as
	// proof that the attachment is fully realized, and reports CNI ADD success
	// only after receiving it.
	//
	// Any failure - including a failure to publish the binding - must leave no
	// interface behind, and is reported as a gRPC error status. The caller
	// fails the CNI ADD; it never falls back to realizing the datapath itself.
	//
	// The call is idempotent for a repeated request that carries the same
	// attachment_id, netns and ifname: a retry of an interrupted CreatePodInterface
	// returns the handle of the interface that already exists for that
	// attachment rather than creating a second one.
	CreatePodInterface(ctx context.Context, in *CreatePodInterfaceRequest, opts ...grpc.CallOption) (*CreatePodInterfaceReply, error)
	// DeletePodInterface revokes the attachment binding and destroys the Pod's
	// interface.
	//
	// It is called on CNI DEL, before the endpoint is deleted from the Cilium
	// agent. NOT_FOUND means the attachment is already gone and is treated by
	// the caller as success, because CNI DEL is retried and must converge.
	DeletePodInterface(ctx context.Context, in *DeletePodInterfaceRequest, opts ...grpc.CallOption) (*DeletePodInterfaceReply, error)
}

type podInterfaceLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPodInterfaceLifecycleClient(cc grpc.ClientConnInterface) PodInterfaceLifecycleClient {
	return &podInterfaceLifecycleClient{cc}
}

func (c *podInterfaceLifecycleClient) CreatePodInterface(ctx context.Context, in *CreatePodInterfaceRequest, opts ...grpc.CallOption) (*CreatePodInterfaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePodInterfaceReply)
	err := c.cc.Invoke(ctx, PodInterfaceLifecycle_CreatePodInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podInterfaceLifecycleClient) DeletePodInterface(ctx context.Context, in *DeletePodInterfaceRequest, opts ...grpc.CallOption) (*DeletePodInterfaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePodInterfaceReply)
	err := c.cc.Invoke(ctx, PodInterfaceLifecycle_DeletePodInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodInterfaceLifecycleServer is the server API for PodInterfaceLifecycle service.
// All implementations must embed UnimplementedPodInterfaceLifecycleServer
// for forward compatibility.
//
// PodInterfaceLifecycle is the contract between Cilium's CNI plugin and an
// external provider that owns the L3 datapath realization of a Pod attachment.
//
// For one Pod attachment, exactly one component owns L3 realization. When this
// service is selected (CNI network configuration field "cniDatapathProvider"),
// Cilium creates no competing veth or netkit datapath for that attachment, and
// the provider is the sole owner of the interface: it creates the device,
// places it in the Pod network namespace, configures the namespace side of it
// and destroys it again.
//
// Cilium remains the authority for everything else about the attachment: the
// CNI attachment identity, IPAM, the endpoint object, its security identity,
// its policy and its lifecycle.
//
// Failures are reported as gRPC status codes. There is no success flag in any
// reply message: a reply that arrives is a reply that succeeded, so that a
// caller cannot mistake a transport-level failure for a refusal or the other
// way round.
type PodInterfaceLifecycleServer interface {
	// CreatePodInterface creates the Pod's interface and makes it usable.
	//
	// A successful reply is a publication barrier. By the time it is sent, the
	// provider has created the interface, has obtained its exact handle, has
	// published the corresponding attachment binding and has received that
	// binding's acknowledgement. The caller may therefore treat the reply as
	// proof that the attachment is fully realized, and reports CNI ADD success
	// only after receiving it.
	//
	// Any failure - including a failure to publish the binding - must leave no
	// interface behind, and is reported as a gRPC error status. The caller
	// fails the CNI ADD; it never falls back to realizing the datapath itself.
	//
	// The call is idempotent for a repeated request that carries the same
	// attachment_id, netns and ifname: a retry of an interrupted CreatePodInterface
	// returns the handle of the interface that already exists for that
	// attachment rather than creating a second one.
	CreatePodInterface(context.Context, *CreatePodInterfaceRequest) (*CreatePodInterfaceReply, error)
	// DeletePodInterface revokes the attachment binding and destroys the Pod's
	// interface.
	//
	// It is called on CNI DEL, before the endpoint is deleted from the Cilium
	// agent. NOT_FOUND means the attachment is already gone and is treated by
	// the caller as success, because CNI DEL is retried and must converge.
	DeletePodInterface(context.Context, *DeletePodInterfaceRequest) (*DeletePodInterfaceReply, error)
	mustEmbedUnimplementedPodInterfaceLifecycleServer()
}

// UnimplementedPodInterfaceLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodInterfaceLifecycleServer struct{}

func (UnimplementedPodInterfaceLifecycleServer) CreatePodInterface(context.Context, *CreatePodInterfaceRequest) (*CreatePodInterfaceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePodInterface not implemented")
}
func (UnimplementedPodInterfaceLifecycleServer) DeletePodInterface(context.Context, *DeletePodInterfaceRequest) (*DeletePodInterfaceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePodInterface not implemented")
}
func (UnimplementedPodInterfaceLifecycleServer) mustEmbedUnimplementedPodInterfaceLifecycleServer() {}
func (UnimplementedPodInterfaceLifecycleServer) testEmbeddedByValue()                               {}

// UnsafePodInterfaceLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodInterfaceLifecycleServer will
// result in compilation errors.
type UnsafePodInterfaceLifecycleServer interface {
	mustEmbedUnimplementedPodInterfaceLifecycleServer()
}

func RegisterPodInterfaceLifecycleServer(s grpc.ServiceRegistrar, srv PodInterfaceLifecycleServer) {
	// If the following call panics, it indicates UnimplementedPodInterfaceLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodInterfaceLifecycle_ServiceDesc, srv)
}

func _PodInterfaceLifecycle_CreatePodInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodInterfaceLifecycleServer).CreatePodInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodInterfaceLifecycle_CreatePodInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodInterfaceLifecycleServer).CreatePodInterface(ctx, req.(*CreatePodInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodInterfaceLifecycle_DeletePodInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodInterfaceLifecycleServer).DeletePodInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodInterfaceLifecycle_DeletePodInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodInterfaceLifecycleServer).DeletePodInterface(ctx, req.(*DeletePodInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodInterfaceLifecycle_ServiceDesc is the grpc.ServiceDesc for PodInterfaceLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodInterfaceLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podinterface.v1.PodInterfaceLifecycle",
	HandlerType: (*PodInterfaceLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePodInterface",
			Handler:    _PodInterfaceLifecycle_CreatePodInterface_Handler,
		},
		{
			MethodName: "DeletePodInterface",
			Handler:    _PodInterfaceLifecycle_DeletePodInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podinterface/podinterface.proto",
}
