// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: podinterface/podinterface.proto

package podinterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreatePodInterfaceRequest asks the provider to realize one Pod attachment.
type CreatePodInterfaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// attachment_id is the CNI attachment identity, verbatim: the identifier
	// Cilium itself uses for this attachment, formed as
	// "<container id>:<container interface name>".
	//
	// It is required and is never re-derived, re-parsed or reconstructed by the
	// provider: the component that knows the identity passes it to the
	// component that knows the interface handle, so that the two never have to
	// be correlated after the fact. It must be between 1 and 255 bytes long and
	// consist of printable ASCII (0x20..0x7e) only. A request that does not
	// satisfy this is rejected with INVALID_ARGUMENT.
	AttachmentId string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// netns is the path of the Pod's network namespace, as the container
	// runtime gave it to the CNI plugin (CNI_NETNS). Required.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// ifname is the name the interface must have inside that network namespace,
	// as the container runtime gave it to the CNI plugin (CNI_IFNAME).
	// Required.
	Ifname string `protobuf:"bytes,3,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// addresses are the addresses to configure on the interface inside the Pod
	// network namespace, in CIDR notation, as allocated by Cilium IPAM. They
	// are host routes: an IPv6 address is a /128 and an IPv4 address is a /32,
	// because the Pod attachment is L3-only and the Pod is not on a shared
	// link with anything.
	//
	// At least one address is required.
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// routes are the destination prefixes, in CIDR notation, to install inside
	// the Pod network namespace. Each one is installed as a device route out of
	// the created interface, with no gateway and no on-link neighbour: the
	// attachment is L3-only, so there is no next hop to resolve.
	//
	// May be empty, in which case the provider installs no routes beyond the
	// ones implied by the addresses.
	Routes []string `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	// mtu is the MTU to set on the interface, in bytes. Required, and must be
	// greater than zero.
	Mtu           uint32 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodInterfaceRequest) Reset() {
	*x = CreatePodInterfaceRequest{}
	mi := &file_podinterface_podinterface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodInterfaceRequest) ProtoMessage() {}

func (x *CreatePodInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodInterfaceRequest.ProtoReflect.Descriptor instead.
func (*CreatePodInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePodInterfaceRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CreatePodInterfaceRequest) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *CreatePodInterfaceRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

// CreatePodInterfaceReply reports the exact handle of the interface that was
// created. Its arrival is the publication barrier described on
// CreatePodInterface.
type CreatePodInterfaceReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sw_if_index is the provider's interface index for the created interface.
	//
	// It is reported for diagnostics and for correlation with the provider's
	// own state. It is not an identifier Cilium resolves anything by: the
	// authoritative association between an attachment and an interface handle
	// travels through the attachment binding the provider published, not
	// through this field.
	SwIfIndex uint32 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	// if_incarnation distinguishes successive interfaces that reuse the same
	// sw_if_index. Together with sw_if_index it forms the exact handle of one
	// interface lifetime, which is what a later revocation must name.
	IfIncarnation uint32 `protobuf:"varint,2,opt,name=if_incarnation,json=ifIncarnation,proto3" json:"if_incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodInterfaceReply) Reset() {
	*x = CreatePodInterfaceReply{}
	mi := &file_podinterface_podinterface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodInterfaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodInterfaceReply) ProtoMessage() {}

func (x *CreatePodInterfaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodInterfaceReply.ProtoReflect.Descriptor instead.
func (*CreatePodInterfaceReply) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePodInterfaceReply) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *CreatePodInterfaceReply) GetIfIncarnation() uint32 {
	if x != nil {
		return x.IfIncarnation
	}
	return 0
}

// DeletePodInterfaceRequest asks the provider to tear one Pod attachment down.
type DeletePodInterfaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// attachment_id is the same CNI attachment identity that was passed to
	// CreatePodInterface, verbatim. Required, and subject to the same
	// constraints.
	AttachmentId string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// netns is the path of the Pod's network namespace. It may no longer exist
	// by the time this call is made; that does not excuse the provider from
	// revoking the binding and destroying the interface.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// ifname is the name of the interface inside that network namespace.
	Ifname        string `protobuf:"bytes,3,opt,name=ifname,proto3" json:"ifname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodInterfaceRequest) Reset() {
	*x = DeletePodInterfaceRequest{}
	mi := &file_podinterface_podinterface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodInterfaceRequest) ProtoMessage() {}

func (x *DeletePodInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodInterfaceRequest.ProtoReflect.Descriptor instead.
func (*DeletePodInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePodInterfaceRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *DeletePodInterfaceRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *DeletePodInterfaceRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

// DeletePodInterfaceReply is empty: the fact that it arrived is the result.
type DeletePodInterfaceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodInterfaceReply) Reset() {
	*x = DeletePodInterfaceReply{}
	mi := &file_podinterface_podinterface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodInterfaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodInterfaceReply) ProtoMessage() {}

func (x *DeletePodInterfaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodInterfaceReply.ProtoReflect.Descriptor instead.
func (*DeletePodInterfaceReply) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{3}
}

var File_podinterface_podinterface_proto protoreflect.FileDescriptor

const file_podinterface_podinterface_proto_rawDesc = "" +
	"\n" +
	"\x1fpodinterface/podinterface.proto\x12\x0fpodinterface.v1\"\xb6\x01\n" +
	"\x19CreatePodInterfaceRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x16\n" +
	"\x06ifname\x18\x03 \x01(\tR\x06ifname\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\"`\n" +
	"\x17CreatePodInterfaceReply\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12%\n" +
	"\x0eif_incarnation\x18\x02 \x01(\rR\rifIncarnation\"n\n" +
	"\x19DeletePodInterfaceRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x16\n" +
	"\x06ifname\x18\x03 \x01(\tR\x06ifname\"\x19\n" +
	"\x17DeletePodInterfaceReply2\xef\x01\n" +
	"\x15PodInterfaceLifecycle\x12j\n" +
	"\x12CreatePodInterface\x12*.podinterface.v1.CreatePodInterfaceRequest\x1a(.podinterface.v1.CreatePodInterfaceReply\x12j\n" +
	"\x12DeletePodInterface\x12*.podinterface.v1.DeletePodInterfaceRequest\x1a(.podinterface.v1.DeletePodInterfaceReplyB.Z,github.com/cilium/cilium/api/v1/podinterfaceb\x06proto3"

var (
	file_podinterface_podinterface_proto_rawDescOnce sync.Once
	file_podinterface_podinterface_proto_rawDescData []byte
)

func file_podinterface_podinterface_proto_rawDescGZIP() []byte {
	file_podinterface_podinterface_proto_rawDescOnce.Do(func() {
		file_podinterface_podinterface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinterface_podinterface_proto_rawDesc), len(file_podinterface_podinterface_proto_rawDesc)))
	})
	return file_podinterface_podinterface_proto_rawDescData
}

var file_podinterface_podinterface_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_podinterface_podinterface_proto_goTypes = []any{
	(*CreatePodInterfaceRequest)(nil), // 0: podinterface.v1.CreatePodInterfaceRequest
	(*CreatePodInterfaceReply)(nil),   // 1: podinterface.v1.CreatePodInterfaceReply
	(*DeletePodInterfaceRequest)(nil), // 2: podinterface.v1.DeletePodInterfaceRequest
	(*DeletePodInterfaceReply)(nil),   // 3: podinterface.v1.DeletePodInterfaceReply
}
var file_podinterface_podinterface_proto_depIdxs = []int32{
	0, // 0: podinterface.v1.PodInterfaceLifecycle.CreatePodInterface:input_type -> podinterface.v1.CreatePodInterfaceRequest
	2, // 1: podinterface.v1.PodInterfaceLifecycle.DeletePodInterface:input_type -> podinterface.v1.DeletePodInterfaceRequest
	1, // 2: podinterface.v1.PodInterfaceLifecycle.CreatePodInterface:output_type -> podinterface.v1.CreatePodInterfaceReply
	3, // 3: podinterface.v1.PodInterfaceLifecycle.DeletePodInterface:output_type -> podinterface.v1.DeletePodInterfaceReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinterface_podinterface_proto_init() }
func file_podinterface_podinterface_proto_init() {
	if File_podinterface_podinterface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinterface_podinterface_proto_rawDesc), len(file_podinterface_podinterface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinterface_podinterface_proto_goTypes,
		DependencyIndexes: file_podinterface_podinterface_proto_depIdxs,
		MessageInfos:      file_podinterface_podinterface_proto_msgTypes,
	}.Build()
	File_podinterface_podinterface_proto = out.File
	file_podinterface_podinterface_proto_goTypes = nil
	file_podinterface_podinterface_proto_depIdxs = nil
}
