// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Cilium Authors

// PodInterfaceLifecycle is the interface between the CNI plugin that owns Pod
// attachment identity and IPAM, and the VPP Pod interface lifecycle owner that
// creates the Pod-facing VPP interface.
//
// The split exists because SRv6 Endpoint Context v1 requires the component that
// creates the interface to publish the CNI attachment identity against the
// exact InterfaceHandle it just created (design/detail/00-overview.md §2.12.6,
// D-71). Making the creation request carry the attachment identity is what
// keeps that requirement satisfiable: neither side has to reconstruct the
// correspondence afterwards from an interface name or a Linux ifindex, which
// §2.12.7 forbids.
//
// CreatePodInterface returns only after the binding has been published and
// acknowledged. The caller MUST NOT report the CNI attachment as successful
// before this reply arrives; the reply is the publication barrier.
//
// Failures are gRPC statuses. There is no "successful" field: a reply that
// exists means the interface was created and its binding published.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.1
// source: podinterface/podinterface.proto

package podinterface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodInterfaceLifecycle_CreatePodInterface_FullMethodName = "/podinterface.v1.PodInterfaceLifecycle/CreatePodInterface"
	PodInterfaceLifecycle_DeletePodInterface_FullMethodName = "/podinterface.v1.PodInterfaceLifecycle/DeletePodInterface"
)

// PodInterfaceLifecycleClient is the client API for PodInterfaceLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodInterfaceLifecycleClient interface {
	CreatePodInterface(ctx context.Context, in *CreatePodInterfaceRequest, opts ...grpc.CallOption) (*CreatePodInterfaceReply, error)
	DeletePodInterface(ctx context.Context, in *DeletePodInterfaceRequest, opts ...grpc.CallOption) (*DeletePodInterfaceReply, error)
}

type podInterfaceLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPodInterfaceLifecycleClient(cc grpc.ClientConnInterface) PodInterfaceLifecycleClient {
	return &podInterfaceLifecycleClient{cc}
}

func (c *podInterfaceLifecycleClient) CreatePodInterface(ctx context.Context, in *CreatePodInterfaceRequest, opts ...grpc.CallOption) (*CreatePodInterfaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePodInterfaceReply)
	err := c.cc.Invoke(ctx, PodInterfaceLifecycle_CreatePodInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podInterfaceLifecycleClient) DeletePodInterface(ctx context.Context, in *DeletePodInterfaceRequest, opts ...grpc.CallOption) (*DeletePodInterfaceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePodInterfaceReply)
	err := c.cc.Invoke(ctx, PodInterfaceLifecycle_DeletePodInterface_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodInterfaceLifecycleServer is the server API for PodInterfaceLifecycle service.
// All implementations must embed UnimplementedPodInterfaceLifecycleServer
// for forward compatibility.
type PodInterfaceLifecycleServer interface {
	CreatePodInterface(context.Context, *CreatePodInterfaceRequest) (*CreatePodInterfaceReply, error)
	DeletePodInterface(context.Context, *DeletePodInterfaceRequest) (*DeletePodInterfaceReply, error)
	mustEmbedUnimplementedPodInterfaceLifecycleServer()
}

// UnimplementedPodInterfaceLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodInterfaceLifecycleServer struct{}

func (UnimplementedPodInterfaceLifecycleServer) CreatePodInterface(context.Context, *CreatePodInterfaceRequest) (*CreatePodInterfaceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePodInterface not implemented")
}
func (UnimplementedPodInterfaceLifecycleServer) DeletePodInterface(context.Context, *DeletePodInterfaceRequest) (*DeletePodInterfaceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePodInterface not implemented")
}
func (UnimplementedPodInterfaceLifecycleServer) mustEmbedUnimplementedPodInterfaceLifecycleServer() {}
func (UnimplementedPodInterfaceLifecycleServer) testEmbeddedByValue()                               {}

// UnsafePodInterfaceLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodInterfaceLifecycleServer will
// result in compilation errors.
type UnsafePodInterfaceLifecycleServer interface {
	mustEmbedUnimplementedPodInterfaceLifecycleServer()
}

func RegisterPodInterfaceLifecycleServer(s grpc.ServiceRegistrar, srv PodInterfaceLifecycleServer) {
	// If the following call panics, it indicates UnimplementedPodInterfaceLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodInterfaceLifecycle_ServiceDesc, srv)
}

func _PodInterfaceLifecycle_CreatePodInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodInterfaceLifecycleServer).CreatePodInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodInterfaceLifecycle_CreatePodInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodInterfaceLifecycleServer).CreatePodInterface(ctx, req.(*CreatePodInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodInterfaceLifecycle_DeletePodInterface_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodInterfaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodInterfaceLifecycleServer).DeletePodInterface(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodInterfaceLifecycle_DeletePodInterface_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodInterfaceLifecycleServer).DeletePodInterface(ctx, req.(*DeletePodInterfaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodInterfaceLifecycle_ServiceDesc is the grpc.ServiceDesc for PodInterfaceLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodInterfaceLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podinterface.v1.PodInterfaceLifecycle",
	HandlerType: (*PodInterfaceLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePodInterface",
			Handler:    _PodInterfaceLifecycle_CreatePodInterface_Handler,
		},
		{
			MethodName: "DeletePodInterface",
			Handler:    _PodInterfaceLifecycle_DeletePodInterface_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podinterface/podinterface.proto",
}
