// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Cilium Authors

// PodInterfaceLifecycle is the interface between the CNI plugin that owns Pod
// attachment identity and IPAM, and the VPP Pod interface lifecycle owner that
// creates the Pod-facing VPP interface.
//
// The split exists because SRv6 Endpoint Context v1 requires the component that
// creates the interface to publish the CNI attachment identity against the
// exact InterfaceHandle it just created (design/detail/00-overview.md §2.12.6,
// D-71). Making the creation request carry the attachment identity is what
// keeps that requirement satisfiable: neither side has to reconstruct the
// correspondence afterwards from an interface name or a Linux ifindex, which
// §2.12.7 forbids.
//
// CreatePodInterface returns only after the binding has been published and
// acknowledged. The caller MUST NOT report the CNI attachment as successful
// before this reply arrives; the reply is the publication barrier.
//
// Failures are gRPC statuses. There is no "successful" field: a reply that
// exists means the interface was created and its binding published.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: podinterface/podinterface.proto

package podinterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePodInterfaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// attachment_id is the completed CNI attachment identity, passed verbatim.
	// It is required, is stored and published without transformation, and is
	// rejected rather than truncated when it is outside 1..255 bytes of
	// printable ASCII (design/detail/02-headend-dataplane.md §8.1 rule 1).
	AttachmentId string `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// netns is the host path of the Pod network namespace.
	Netns string `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	// ifname is the interface name to create inside the Pod netns.
	Ifname string `protobuf:"bytes,3,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// addresses are the Pod addresses in CIDR form, as decided by the caller's
	// IPAM. Each address is a host address (/128).
	Addresses []string `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// routes are the routes to install inside the Pod netns, in CIDR form.
	Routes []string `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	// mtu is the MTU to configure on the Pod-side interface.
	Mtu           uint32 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodInterfaceRequest) Reset() {
	*x = CreatePodInterfaceRequest{}
	mi := &file_podinterface_podinterface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodInterfaceRequest) ProtoMessage() {}

func (x *CreatePodInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodInterfaceRequest.ProtoReflect.Descriptor instead.
func (*CreatePodInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePodInterfaceRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *CreatePodInterfaceRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CreatePodInterfaceRequest) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *CreatePodInterfaceRequest) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type CreatePodInterfaceReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sw_if_index and if_incarnation are the InterfaceHandle the binding was
	// published against. They are returned for observability; the caller is not
	// expected to resolve anything with them.
	SwIfIndex     uint32 `protobuf:"varint,1,opt,name=sw_if_index,json=swIfIndex,proto3" json:"sw_if_index,omitempty"`
	IfIncarnation uint32 `protobuf:"varint,2,opt,name=if_incarnation,json=ifIncarnation,proto3" json:"if_incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodInterfaceReply) Reset() {
	*x = CreatePodInterfaceReply{}
	mi := &file_podinterface_podinterface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodInterfaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodInterfaceReply) ProtoMessage() {}

func (x *CreatePodInterfaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodInterfaceReply.ProtoReflect.Descriptor instead.
func (*CreatePodInterfaceReply) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePodInterfaceReply) GetSwIfIndex() uint32 {
	if x != nil {
		return x.SwIfIndex
	}
	return 0
}

func (x *CreatePodInterfaceReply) GetIfIncarnation() uint32 {
	if x != nil {
		return x.IfIncarnation
	}
	return 0
}

type DeletePodInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	Netns         string                 `protobuf:"bytes,2,opt,name=netns,proto3" json:"netns,omitempty"`
	Ifname        string                 `protobuf:"bytes,3,opt,name=ifname,proto3" json:"ifname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodInterfaceRequest) Reset() {
	*x = DeletePodInterfaceRequest{}
	mi := &file_podinterface_podinterface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodInterfaceRequest) ProtoMessage() {}

func (x *DeletePodInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodInterfaceRequest.ProtoReflect.Descriptor instead.
func (*DeletePodInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePodInterfaceRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *DeletePodInterfaceRequest) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

func (x *DeletePodInterfaceRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

// DeletePodInterfaceReply is empty: a NOT_FOUND status, not a field, reports
// that the attachment is unknown, and the caller treats that as an idempotent
// success.
type DeletePodInterfaceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodInterfaceReply) Reset() {
	*x = DeletePodInterfaceReply{}
	mi := &file_podinterface_podinterface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodInterfaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodInterfaceReply) ProtoMessage() {}

func (x *DeletePodInterfaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_podinterface_podinterface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodInterfaceReply.ProtoReflect.Descriptor instead.
func (*DeletePodInterfaceReply) Descriptor() ([]byte, []int) {
	return file_podinterface_podinterface_proto_rawDescGZIP(), []int{3}
}

var File_podinterface_podinterface_proto protoreflect.FileDescriptor

const file_podinterface_podinterface_proto_rawDesc = "" +
	"\n" +
	"\x1fpodinterface/podinterface.proto\x12\x0fpodinterface.v1\"\xb6\x01\n" +
	"\x19CreatePodInterfaceRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x16\n" +
	"\x06ifname\x18\x03 \x01(\tR\x06ifname\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\rR\x03mtu\"`\n" +
	"\x17CreatePodInterfaceReply\x12\x1e\n" +
	"\vsw_if_index\x18\x01 \x01(\rR\tswIfIndex\x12%\n" +
	"\x0eif_incarnation\x18\x02 \x01(\rR\rifIncarnation\"n\n" +
	"\x19DeletePodInterfaceRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x14\n" +
	"\x05netns\x18\x02 \x01(\tR\x05netns\x12\x16\n" +
	"\x06ifname\x18\x03 \x01(\tR\x06ifname\"\x19\n" +
	"\x17DeletePodInterfaceReply2\xef\x01\n" +
	"\x15PodInterfaceLifecycle\x12j\n" +
	"\x12CreatePodInterface\x12*.podinterface.v1.CreatePodInterfaceRequest\x1a(.podinterface.v1.CreatePodInterfaceReply\x12j\n" +
	"\x12DeletePodInterface\x12*.podinterface.v1.DeletePodInterfaceRequest\x1a(.podinterface.v1.DeletePodInterfaceReplyB;Z9github.com/cilium/cilium/api/v1/podinterface;podinterfaceb\x06proto3"

var (
	file_podinterface_podinterface_proto_rawDescOnce sync.Once
	file_podinterface_podinterface_proto_rawDescData []byte
)

func file_podinterface_podinterface_proto_rawDescGZIP() []byte {
	file_podinterface_podinterface_proto_rawDescOnce.Do(func() {
		file_podinterface_podinterface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podinterface_podinterface_proto_rawDesc), len(file_podinterface_podinterface_proto_rawDesc)))
	})
	return file_podinterface_podinterface_proto_rawDescData
}

var file_podinterface_podinterface_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_podinterface_podinterface_proto_goTypes = []any{
	(*CreatePodInterfaceRequest)(nil), // 0: podinterface.v1.CreatePodInterfaceRequest
	(*CreatePodInterfaceReply)(nil),   // 1: podinterface.v1.CreatePodInterfaceReply
	(*DeletePodInterfaceRequest)(nil), // 2: podinterface.v1.DeletePodInterfaceRequest
	(*DeletePodInterfaceReply)(nil),   // 3: podinterface.v1.DeletePodInterfaceReply
}
var file_podinterface_podinterface_proto_depIdxs = []int32{
	0, // 0: podinterface.v1.PodInterfaceLifecycle.CreatePodInterface:input_type -> podinterface.v1.CreatePodInterfaceRequest
	2, // 1: podinterface.v1.PodInterfaceLifecycle.DeletePodInterface:input_type -> podinterface.v1.DeletePodInterfaceRequest
	1, // 2: podinterface.v1.PodInterfaceLifecycle.CreatePodInterface:output_type -> podinterface.v1.CreatePodInterfaceReply
	3, // 3: podinterface.v1.PodInterfaceLifecycle.DeletePodInterface:output_type -> podinterface.v1.DeletePodInterfaceReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podinterface_podinterface_proto_init() }
func file_podinterface_podinterface_proto_init() {
	if File_podinterface_podinterface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podinterface_podinterface_proto_rawDesc), len(file_podinterface_podinterface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinterface_podinterface_proto_goTypes,
		DependencyIndexes: file_podinterface_podinterface_proto_depIdxs,
		MessageInfos:      file_podinterface_podinterface_proto_msgTypes,
	}.Build()
	File_podinterface_podinterface_proto = out.File
	file_podinterface_podinterface_proto_goTypes = nil
	file_podinterface_podinterface_proto_depIdxs = nil
}
