#!/bin/bash
# Copyright (C) 2026 Cilium Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Refresh the vendored snapshot of the PodInterfaceLifecycle proto.
#
# The canonical source of the contract is api/v1/podinterface/podinterface.proto
# in the Cilium repository: Cilium is the caller and the side that specifies the
# contract, so this repository only ever holds a snapshot of it.  The rule is
# the one applied to the cilium_srv6 plugin snapshot (decision 7 of Issue #135):
# one canonical source, a pinned commit, and a mechanical equality check.
#
# The authority is the commit SHA this script records, not a pull request
# number: a pull request can be rebased, retargeted or renumbered, and its
# number does not name a file's contents.  scripts/check-podinterface-proto-sync.sh
# verifies the snapshot against exactly the commit pinned here.
#
# Usage:
#   scripts/sync-podinterface-proto.sh <cilium-repo-path> [<commit-ish>]
#
#   <cilium-repo-path>  path to a checkout of the Cilium repository
#   <commit-ish>        commit to take the snapshot from (default: HEAD of the
#                       given checkout).  The snapshot is read from the git
#                       object store, not from the working tree, so an unclean
#                       working tree cannot leak into it.

set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPODIR="$(cd "$SCRIPTDIR/.." >/dev/null 2>&1 && pwd)"

# Path of the canonical proto inside the Cilium repository.
CILIUM_PROTO_PATH="api/v1/podinterface/podinterface.proto"
# Destination of the snapshot inside this repository.
DEST_FILE="$REPODIR/calico-vpp-agent/proto/podinterface/podinterface.proto"
# Pin file recording the canonical commit the snapshot was taken from.
PIN_FILE="$REPODIR/calico-vpp-agent/proto/PODINTERFACE_PROTO_SOURCE"

function red() { printf "\e[0;31m%s\e[0m\n" "$1" >&2; }
function green() { printf "\e[0;32m%s\e[0m\n" "$1" >&2; }

if [ $# -lt 1 ]; then
	red "usage: $0 <cilium-repo-path> [<commit-ish>]"
	exit 1
fi

CILIUM_DIR="$1"
COMMITISH="${2:-HEAD}"

if [ ! -e "$CILIUM_DIR/.git" ]; then
	red "$CILIUM_DIR is not a git repository"
	exit 1
fi

COMMIT="$(git -C "$CILIUM_DIR" rev-parse "$COMMITISH^{commit}")"

if ! git -C "$CILIUM_DIR" cat-file -e "$COMMIT:$CILIUM_PROTO_PATH" 2>/dev/null; then
	red "$CILIUM_PROTO_PATH does not exist at $COMMIT in $CILIUM_DIR"
	exit 1
fi

green "Snapshotting $CILIUM_PROTO_PATH from $COMMIT"

mkdir -p "$(dirname "$DEST_FILE")"
git -C "$CILIUM_DIR" show "$COMMIT:$CILIUM_PROTO_PATH" >"$DEST_FILE"

cat >"$PIN_FILE" <<EOF
# Canonical source of podinterface/podinterface.proto.
#
# The PodInterfaceLifecycle contract is required by, and specified from, the
# Cilium side (Cilium is the caller), so the canonical proto file lives in the
# Cilium repository and this repository holds a snapshot of it. The rule is the
# same one applied to the cilium_srv6 plugin snapshot (Issue #135 decision 7):
# one canonical source, a pinned commit, and a mechanical equality check.
#
# The snapshot keeps the canonical file's \`go_package\`; the Go import path used
# here is remapped at generation time by calico-vpp-agent/proto/Makefile, so the
# .proto file itself can stay byte-identical to the canonical one.
#
# Written by scripts/sync-podinterface-proto.sh. Do not edit this file or the
# snapshot by hand: scripts/check-podinterface-proto-sync.sh fails when they
# differ from the pinned commit by a single byte.
#
# PODINTERFACE_PROTO_SOURCE_COMMIT is the only authority for which version of the
# contract this snapshot is. A pull request number is not: a pull request can be
# rebased, retargeted or renumbered, and it does not name a file's contents.
PODINTERFACE_PROTO_SOURCE_REPO=https://github.com/ryskn/cilium-private.git
PODINTERFACE_PROTO_SOURCE_PATH=$CILIUM_PROTO_PATH
PODINTERFACE_PROTO_SOURCE_COMMIT=$COMMIT
EOF

green "Wrote $PIN_FILE"
green "Snapshot refreshed. Regenerate the Go bindings with 'make -C calico-vpp-agent/proto proto'."
